#!/usr/bin/env bash
#This is the configure of the HAProxy
apt-get -y update
apt-get -y install haproxy
varf="\
frontend http_front
    bind *:80
    mode http
    default_backend http_back

backend http_back
    balance roundrobin
    server 1101-web-01 54.237.196.98:80 check
    server 1101-web-02 104.196.27.193:80 check"
echo "$varf" >> /etc/haproxy/haproxy.cfg
service haproxy start
