#!/usr/bin/env bash
# use echo to print the msg
c=0
while [ $c -le 9 ]
do
    if [ $c -eq 3 ]
    then
	echo "bad luck"
    elif [ $c -eq 7 ]
    then
	echo "good luck"
    else
	echo "Holberton School"
    fi
    ((c++))
done
